#pragma once

#define PHYSICS_CATEGORY Definitions::PhysicsCategory

namespace Definitions
{
	enum class PhysicsCategory
	{
		PHYSICS_CATEGORY_NONE		= 0,
		PHYSICS_CATEGORY_ALIEN_SHIP = (1 << 0),
		PHYSICS_CATEGORY_PROJECTILE = (1 << 1),
		PHYSICS_CATEGORY_PROJECTILE_ALL = PHYSICS_CATEGORY::PHYSICS_CATEGORY_ALIEN_SHIP | PHYSICS_CATEGORY::PHYSICS_CATEGORY_PROJECTILE
	};
}